services:
  api:
    image: "accounting"
    build:
      context: .
      dockerfile: Dockerfile.accounting
    depends_on:
      - migrator
      - db
    ports:
      - 44044:8080
  migrator:
    image: migrator
    build:
      context: .
      dockerfile: Dockerfile.migrator
    depends_on:
      - db
    restart: "no"
  db:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - 44045:5432
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db: